/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import io.opentelemetry.api.GlobalOpenTelemetry;
import io.opentelemetry.api.trace.Span;
import io.opentelemetry.api.trace.Tracer;
import io.opentelemetry.exporter.logging.LoggingSpanExporter;
import io.opentelemetry.exporter.otlp.http.trace.OtlpHttpSpanExporter;
import io.opentelemetry.sdk.OpenTelemetrySdk;
import io.opentelemetry.sdk.trace.SdkTracerProvider;
import io.opentelemetry.sdk.trace.export.SimpleSpanProcessor;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    // Configure Jaeger exporter
    OtlpHttpSpanExporter jaegerExporter = OtlpHttpSpanExporter.builder()
        .setEndpoint("http://localhost:65107")
        .build();

    // Set up the SDK tracer provider
    SdkTracerProvider tracerProvider = SdkTracerProvider.builder()
        .addSpanProcessor(SimpleSpanProcessor.create(LoggingSpanExporter.create()))
        .addSpanProcessor(SimpleSpanProcessor.create(jaegerExporter))
        .build();

    // Initialize the OpenTelemetry SDK
    var sdk = OpenTelemetrySdk.builder().setTracerProvider(tracerProvider).buildAndRegisterGlobal();

    // Create a tracer
    Tracer tracer = sdk.getTracer("demo");

    // Create a span
    Span span = tracer.spanBuilder("my-first-span").startSpan();

    // Simulate work inside the span
    span.addEvent("Doing some work here");

    // End the span
    span.end();

    System.out.println("Trace has been sent to Jaeger!");
    tracerProvider.shutdown();
  }
}
