version: "3"

services:
  prometheus2:
    image: quay.io/prometheus/prometheus:v2.54.1
    container_name: prometheus2
    ports:
      - "9090:9090"
    environment:
      - PROMETHEUS_STORAGE_TSDB_PATH=/prometheus
      - PROMETHEUS_WEB_ENABLE_ADMIN_API=true
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # 挂载Prometheus配置文件
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'   # 启用生命周期接口，支持热更新配置
      - '--storage.tsdb.retention.time=15d'   # 数据保留15天
  jaeger2:
    image: jaegertracing/all-in-one:1.60 # 最新的 Jaeger 镜像
    command:
      - "--prometheus.server-url=http://172.31.80.1:9090"
    container_name: jaeger2
    ports:
      - "16686:16686" # Jaeger UI
      - "6831:6831/udp" # UDP for Jaeger agent
      - "14250:14250" # gRPC for Jaeger agent
      - "14268:14268" # HTTP for Jaeger collector
      - "4317:4317" # gRPC server
      - "4318:4318" # HTTP server
    environment:
      - METRICS_STORAGE_TYPE=prometheus
      - JAEGER_SAMPLER_TYPE=const
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411 # 兼容 Zipkin 的 API 端口
    network_mode: bridge