receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlp:
    endpoint: "jaeger2:4317"  # Jaeger 的 HTTP 端点

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp, logging]  # 使用 otlphttp 导出器和日志导出器
